/**
 * @author 王镇佳<wzjfloor@163.com
 * Date: 17/04/17
 */
export const MOVIES_LIST = 'MOVIES_LIST'
export const MOVING_DETAIL = 'MOVING_DETAIL'
export const MOVING_ID = 'MOVING_ID'
export const LOGIN_DIALOG_VISIBLE = 'LOGIN_DIALOG_VISIBLE'
export const REGISTER_DIALOG_VISIBLE = 'REGISTER_DIALOG_VISIBLE'
export const SELECT_SEAT_DIALOG_VISIBLE = 'SELECT_SEAT_DIALOG_VISIBLE'
export const LOGIN_USER = 'LOGIN_USER'